- name: install nginx
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - nginx
  become: true
- name: disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  notify: restart nginx
