- template:
    src: app.ini
    dest: /home/vagrant/app/production.ini
  notify: restart app
- template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/app.conf
    owner: root
  become: true
  notify: restart nginx
- template:
    src: startup.conf
    dest: /etc/init/app.conf
    owner: root
  become: true
- file:
    path: /etc/nginx/sites-enabled/app.conf
    src: /etc/nginx/sites-available/app.conf
    state: link
  become: true
- pip:
    virtualenv: /home/vagrant/app/env
    name: "{{item}}"
    state: latest
  with_items:
    - uwsgi
    - flask
