- name: make tar
  local_action: shell tar czf app.tar.gz app
- copy:
    src: app.tar.gz
    dest: /home/vagrant/app/app.tar.gz
- shell: "cd /home/vagrant/app && tar xzf app.tar.gz"
  notify: restart app
